// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // Si tu n'as pas configuré le Web, on garde l'erreur ou on retourne android par défaut (déconseillé)
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      // Si tu testes sur iPhone plus tard, il faudra ajouter la constante 'ios' ici
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Ta configuration Android actuelle (Project ID: sae-s4-757c8)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyIgJw8vQ2BRZB8vyJfWBgGesimk-3WHA',
    appId: '1:504707262443:android:ff70fa0615b944815a5bae',
    messagingSenderId: '504707262443',
    projectId: 'sae-s4-757c8',
    storageBucket: 'sae-s4-757c8.firebasestorage.app',
  );
}